version: '3.2'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - .:/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gistda.or.th
      PGADMIN_DEFAULT_PASSWORD: 123456
      MAX_LOGIN_ATTEMPTS: 1000
    ports:
      - "5050:80"
    volumes:
       - pgadmin:/var/lib/pgadmin

volumes:
    pgadmin:
    db:
